name: Github Release

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8

      - name: Get release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

      - name: Build Slate Doc
        run: |
          sed -i "s/VERSION/$RELEASE_VERSION/g" slate/source/index.html.md
          docker build -t slate-builder:latest slate/
          docker run --rm -v $(pwd)/static:/srv/slate/build slate-builder:latest

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
